"""add intent column to messages

Revision ID: 0eada260e26b
Revises: 10fc3c2df820
Create Date: 2026-01-22 12:21:48.579753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0eada260e26b'
down_revision: Union[str, Sequence[str], None] = '10fc3c2df820'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('intent', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'intent')
    # ### end Alembic commands ###
